server:
  port: 8088
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: false
  task:
    execution:
      pool:
        core-size: 5          # 核心线程数
        max-size: 10          # 最大线程数
        queue-capacity: 100   # 队列容量
        allow-core-thread-timeout: true
      thread-name-prefix: "async-"
    scheduling:
      pool:
        size: 5               # 调度线程池大小
      thread-name-prefix: "scheduler-"
  redis:
    host: localhost
    port: 6379
  application:
    name: mqtt
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mqtt?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: *******
    type: com.alibaba.druid.pool.DruidDataSource
  web:
    resources:
      static-locations: ""  # 清空默认路径（/static, /public等）
      add-mappings: false   # 禁用所有静态资源映射
  mail:
    host: smtp.qq.com
    port: 587
    username: 1564549374@qq.com
    password: ***********
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true



mybatis-plus:
  mapper-locations: classpath*:com/zju/mqtt/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    aggressive-lazy-loading: true
  global-config:
    db-config:
      id-type: ASSIGN_ID


jwt:
  expiration: 86400000 # 单位为ms，1day
